"""
analyzer.py

Responsible for sending prompts to the configured AI provider
(OpenAI or Gemini) and returning the raw text response.
This module does NOT know anything about resumes, JSON parsing,
or scoring — it only knows how to talk to an AI API.
"""

import json
import re
from typing import Optional
"""
Add this near the top of analyzer.py, after the imports.
"""

class ResumeAnalysisError(Exception):
    """Base exception for any failure during resume analysis."""
    pass


class AIProviderError(ResumeAnalysisError):
    """Raised when the AI API call itself fails (network, auth, rate limit)."""
    pass


class ResponseParsingError(ResumeAnalysisError):
    """Raised when the AI responded, but we couldn't parse usable JSON from it."""
    pass

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

try:
    import google.generativeai as genai
except ImportError:
    genai = None

import config
from prompts import build_analysis_prompt


def _call_openai(prompt: str) -> str:
    """Sends a prompt to OpenAI's API and returns the raw text response."""
    if OpenAI is None:
        raise ImportError(
            "The 'openai' package is not installed. Please run 'pip install openai' to use the OpenAI provider."
        )

    client = OpenAI(api_key=config.OPENAI_API_KEY)

    response = client.chat.completions.create(
        model=config.OPENAI_MODEL,
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.4,
    )

    return response.choices[0].message.content


def _call_gemini(prompt: str) -> str:
    """Sends a prompt to Gemini's API and returns the raw text response."""
    if genai is None:
        raise ImportError(
            "The 'google-generativeai' package is not installed. Please run 'pip install google-generativeai' to use the Gemini provider."
        )

    genai.configure(api_key=config.GEMINI_API_KEY)
    model = genai.GenerativeModel(config.GEMINI_MODEL)

    response = model.generate_content(prompt)

    return response.text


def get_ai_response(prompt: str) -> str:
    """
    Sends a prompt to whichever AI provider is configured in config.py,
    and returns the model's raw text response.

    Args:
        prompt: The complete prompt string to send to the AI.

    Returns:
        The raw text response generated by the AI model.

    Raises:
        ValueError: If an unsupported provider is configured.
    """
    if config.AI_PROVIDER == "openai":
        return _call_openai(prompt)
    elif config.AI_PROVIDER == "gemini":
        return _call_gemini(prompt)
    else:
        raise ValueError(f"Unsupported AI_PROVIDER: {config.AI_PROVIDER}")


def _extract_json_block(raw_text: str) -> str:
    """
    Isolates the JSON object from a raw AI response, stripping away
    any markdown code fences or extra text the model may have added
    despite instructions not to.

    Args:
        raw_text: The raw text response from the AI model.

    Returns:
        A string containing (hopefully) only the JSON object.
    """
    # Remove markdown code fences like ```json ... ``` or ``` ... ```
    cleaned = re.sub(r"```json|```", "", raw_text).strip()

    # Find the first '{' and the last '}' to isolate the JSON object,
    # in case the model added any stray text before/after it
    start = cleaned.find("{")
    end = cleaned.rfind("}")

    if start == -1 or end == -1 or end < start:
        return cleaned  # nothing that looks like JSON was found

    return cleaned[start:end + 1]


def parse_ai_response(raw_text: str) -> Optional[dict]:
    """
    Attempts to parse the AI's raw text response into a Python dictionary.

    Args:
        raw_text: The raw text returned by the AI model.

    Returns:
        A dictionary if parsing succeeded, otherwise None.
    """
    json_block = _extract_json_block(raw_text)

    try:
        return json.loads(json_block)
    except json.JSONDecodeError as e:
        print(f"Failed to parse AI response as JSON: {e}")
        return None


def analyze_resume(resume_text: str) -> dict:
    """
    Runs the full resume analysis pipeline: builds the prompt, calls the
    AI model, and parses the result into a structured dictionary.

    Args:
        resume_text: The cleaned resume text to analyze.

    Returns:
        A dictionary containing the structured analysis
        (ats_score, skills_found, strengths, etc.).

    Raises:
        ValueError: If the AI response could not be parsed as valid JSON.
    """
    prompt = build_analysis_prompt(resume_text)
    raw_response = get_ai_response(prompt)

    parsed = parse_ai_response(raw_response)

    if parsed is None:
        raise ValueError(
            "The AI response could not be parsed as valid JSON. "
            "This can happen occasionally — please try again."
        )

    return parsed


from ats import calculate_ats_score
from skills import detect_skills
from prompts import build_improvement_prompt, build_interview_questions_prompt


def run_full_analysis(resume_text: str) -> dict:
    """
    Runs the complete resume analysis pipeline: base AI analysis,
    rule-based ATS scoring, rule-based skill detection, grounded
    improvement suggestions, and grounded interview questions.

    Args:
        resume_text: The cleaned resume text.

    Returns:
        A single merged dictionary containing all analysis results.
    """
    # Step 1: Base AI analysis (Lesson 9)
    ai_result = analyze_resume(resume_text)

    # Step 2: Our own deterministic skill detection (Lesson 11)
    detected_skills = detect_skills(resume_text)

    # Step 3: Our own deterministic ATS scoring (Lesson 10)
    ats_result = calculate_ats_score(resume_text, detected_skills)

    # Step 4: Grounded improvement suggestions (Lesson 12)
    improvement_prompt = build_improvement_prompt(
        resume_text,
        ats_result["total_score"],
        ats_result["breakdown"],
        detected_skills,
        ai_result.get("missing_skills", []),
    )
    improvement_data = parse_ai_response(get_ai_response(improvement_prompt)) or {}

    # Step 5: Grounded interview questions (Lesson 13)
    interview_prompt = build_interview_questions_prompt(
        resume_text,
        detected_skills,
        ai_result.get("missing_skills", []),
    )
    interview_data = parse_ai_response(get_ai_response(interview_prompt)) or {}

    # Step 6: Merge everything into one结果 dictionary for the UI
    return {
        "ai_analysis": ai_result,
        "rule_based_ats": ats_result,
        "detected_skills": detected_skills,
        "improvement_suggestions": improvement_data.get("improvement_suggestions", []),
        "interview_questions": interview_data.get("interview_questions", []),
    }


def _call_openai(prompt: str) -> str:
    """Sends a prompt to OpenAI's API and returns the raw text response."""
    try:
        client = OpenAI(api_key=config.OPENAI_API_KEY)
        response = client.chat.completions.create(
            model=config.OPENAI_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.4,
        )
        return response.choices[0].message.content

    except Exception as e:
        raise AIProviderError(f"OpenAI request failed: {e}") from e


def _call_gemini(prompt: str) -> str:
    """Sends a prompt to Gemini's API and returns the raw text response."""
    try:
        genai.configure(api_key=config.GEMINI_API_KEY)
        model = genai.GenerativeModel(config.GEMINI_MODEL)
        response = model.generate_content(prompt)
        return response.text

    except Exception as e:
        raise AIProviderError(f"Gemini request failed: {e}") from e


def run_full_analysis(resume_text: str) -> dict:
    """
    Runs the complete resume analysis pipeline. The base AI analysis
    (Step 1) must succeed, or the whole function fails. Steps 4-5
    (grounded suggestions/questions) are treated as "best effort" —
    if either fails, we degrade gracefully rather than losing
    everything already computed.
    """
    # Step 1: Base AI analysis — if THIS fails, we have nothing useful
    # to show the user, so we let the exception propagate up.
    ai_result = analyze_resume(resume_text)

    # Step 2 & 3: Our own deterministic logic — no AI involved, very
    # unlikely to fail, but wrapped anyway for safety.
    detected_skills = detect_skills(resume_text)
    ats_result = calculate_ats_score(resume_text, detected_skills)

    # Step 4: Grounded improvement suggestions — best effort.
    improvement_suggestions = []
    try:
        improvement_prompt = build_improvement_prompt(
            resume_text,
            ats_result["total_score"],
            ats_result["breakdown"],
            detected_skills,
            ai_result.get("missing_skills", []),
        )
        improvement_data = parse_ai_response(get_ai_response(improvement_prompt))
        if improvement_data:
            improvement_suggestions = improvement_data.get("improvement_suggestions", [])
    except AIProviderError:
        # Fall back to the AI's own suggestions from Step 1, if present,
        # rather than showing nothing at all.
        improvement_suggestions = ai_result.get("improvement_suggestions", [])

    # Step 5: Grounded interview questions — best effort, same pattern.
    interview_questions = []
    try:
        interview_prompt = build_interview_questions_prompt(
            resume_text, detected_skills, ai_result.get("missing_skills", [])
        )
        interview_data = parse_ai_response(get_ai_response(interview_prompt))
        if interview_data:
            interview_questions = interview_data.get("interview_questions", [])
    except AIProviderError:
        # Fall back to Step 1's plain-string questions, reshaped to match
        # our richer schema so app.py doesn't need special-case handling.
        interview_questions = [
            {"question": q, "type": "general", "based_on": "base analysis"}
            for q in ai_result.get("interview_questions", [])
        ]

    return {
        "ai_analysis": ai_result,
        "rule_based_ats": ats_result,
        "detected_skills": detected_skills,
        "improvement_suggestions": improvement_suggestions,
        "interview_questions": interview_questions,
    }